In [1]:
import numpy as np

In [2]:
data = np.load("valid_100K_disc0.99.npz")

In [3]:
all_observations = data['observations']
all_observations.shape

(108262, 11, 11, 18)

In [4]:
all_actions = data['actions']
all_actions.shape

(108262,)

In [5]:
all_rewards = data['rewards']
all_rewards.shape

(108262,)

In [6]:
obs_stuck = np.all(all_observations[1:] == all_observations[:-1], axis=(1,2,3))
sum(obs_stuck)

15509

In [7]:
obs_stuck2 = np.logical_and(obs_stuck[:-1], obs_stuck[1:])
sum(obs_stuck2)

13419

In [8]:
obs_stuck3 = np.logical_and(obs_stuck[:-2], np.logical_and(obs_stuck[1:-1], obs_stuck[2:]))
sum(obs_stuck3)

12657

In [9]:
obs_stuck4 = np.logical_and(obs_stuck[:-3], np.logical_and(obs_stuck[1:-2], np.logical_and(obs_stuck[2:-1], obs_stuck[3:])))
sum(obs_stuck4)

12329

In [10]:
act_stuck2 = (all_actions[:-1] == all_actions[1:])
sum(act_stuck2)

52496

In [11]:
stuck2 = np.logical_and(obs_stuck2, act_stuck2[:-1])
sum(stuck2)

13394

In [12]:
act_stuck3 = np.logical_and(all_actions[:-2] == all_actions[1:-1], all_actions[:-2] == all_actions[2:])
sum(act_stuck3)

36767

In [13]:
stuck3 = np.logical_and(obs_stuck3, act_stuck3[:-1])
sum(stuck3)

12639

In [14]:
act_stuck4 = \
    np.logical_and(
        np.logical_and(
            all_actions[:-3] == all_actions[1:-2], 
            all_actions[:-3] == all_actions[2:-1]), 
        all_actions[:-3] == all_actions[3:])
sum(act_stuck4)

30329

In [15]:
stuck4 = np.logical_and(obs_stuck4, act_stuck4[:-1])
sum(stuck4)

12315

In [16]:
ind = np.where(stuck3)

In [17]:
np.histogram(all_actions[ind], bins=range(7))[0]

array([4851, 2835, 1355, 2012, 1586,    0])

In [18]:
np.histogram(all_actions, bins=range(7))[0]

array([26224, 20963, 18259, 19520, 19438,  3858])

In [19]:
cleaned_actions = np.delete(all_actions, ind, axis=0)
cleaned_actions.shape

(95623,)

In [20]:
np.histogram(cleaned_actions, bins=range(7))[0]

array([21373, 18128, 16904, 17508, 17852,  3858])

In [21]:
cleaned_observations = np.delete(all_observations, ind, axis=0)
cleaned_observations.shape

(95623, 11, 11, 18)

In [22]:
cleaned_rewards = np.delete(all_rewards, ind, axis=0)
cleaned_rewards.shape

(95623,)

In [23]:
np.savez_compressed("valid_100K_disc0.99_cleaned.npz", observations=cleaned_observations, actions=cleaned_actions, rewards=cleaned_rewards)